---
driver:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true
  chef_output_format: <%= ENV['CHEF_OUTPUT_FORMAT'] || 'minimal' %>
  always_update_cookbooks: true
  chef_license: accept-no-persist
  client_rb:
    rubygems_url: %KTCHN_RBY_URL%
    ssl_verify_mode: none

transport:
  name: dokken

verifier:
  name: inspec
  format: documentation
  
.centos_7_driver_defaults: &centos_7_driver_defaults
  image: %KTCHN_DKKN_IMAGE%
  pid_one_command: /usr/lib/systemd/systemd
  privileged: true # because Docker and SystemD/Upstart

platforms:
  - name: centos-7-chef-12
    driver:
      <<: *centos_7_driver_defaults
      chef_version: 12.21.4
  - name: centos-7-chef-14
    driver:
      <<: *centos_7_driver_defaults
      chef_version: 14.1.12

suites:
  - name: habitat_test
    run_list:
      - recipe[habitat_test]
    attributes:
      %APP_CB_NAME%:
        channel: unstable
